version: '3.8'

services:
  redis:
    image: redislabs/redisearch:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
    command: >
      sh -c "
        redis-server --loadmodule /usr/lib/redis/modules/redisearch.so
      "
